# -*- coding: utf-8 -*-
"""Assignment 1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UUmjBpq6AR39tBFJQmyr8YaMaTm_QKK-
"""

list_ln=["Micheal","Bob","Jhon"]
list_fn=["Johns","Allen","Wick"]
list_lnfn=[]
if (len(list_ln)==len(list_fn)):
  for x in range(0,len(list_ln)):
    list_lnfn.append(list_ln[x]+list_fn[x])
  print(list_lnfn)  
else:
  print("error")